name: The Invisible Everlasting
favicon: null
layout_spectrum: 0.05145
typography_spectrum: 0.16450134431943297
title: Valuing and responding to the eternal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090000'
    - '#5b4a44'
    - '#c1d1d9'
    - '#52c0ec'
    - '#967959'
  brandStrength: 0.9409990848507732
  lightness: 0.17180708120577037
  saturation: 0.789558372925967
  rhythmicContrast: 0.6478488931898028
purpose: []
