name: The Invisible Everlasting
favicon: null
layout_spectrum: 0.05145
typography_spectrum: 0.16450134431943297
title: Valuing and responding to the eternal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272727'
    - '#e7e7e7'
    - '#bfbfbf'
    - '#9e9e9e'
    - '#808080'
  brandStrength: 0.9409990848507732
  lightness: 0.17180708120577037
  saturation: 0.789558372925967
  rhythmicContrast: 0.6478488931898028
purpose: []
